# align.py: align the sung lines of assets/lyrics.txt to tools/whisper_words.json and write src/timing.js.
# Words whisper heard are matched with difflib; the rest are interpolated inside their line. Lines whisper
# could not hear (the chorus wail, the echoes) or got wrong are pinned by ANCHORS below, found by ear and from
# chunked re-transcriptions.
#   python3 tools/align.py [--report]
import json, re, sys, difflib

BPM, OFF = 93.0, 0.568            # beat grid from spectral-flux autocorrelation (steady through the whole song)

raw = open('assets/lyrics.txt').read().split('\n--')[0].splitlines()
lines = [l.strip() for l in raw if l.strip() and not l.strip().startswith('[')]
norm = lambda w: re.sub(r'[^a-z0-9]', '', w.lower().replace('100%', '100'))
toks = [[w for w in l.split() if norm(w)] for l in lines]

ww = json.load(open('tools/whisper_words.json'))
wn = [norm(w) for _, _, w in ww]
flat = [(li, wi, norm(w)) for li, ws in enumerate(toks) for wi, w in enumerate(ws)]
sm = difflib.SequenceMatcher(None, [f[2] for f in flat], wn, autojunk=False)
times = {}
for a, b, n in sm.get_matching_blocks():
    for k in range(n): times[flat[a + k][:2]] = ww[b + k][0]

# (line text prefix, occurrence, [(word index, time), ...]): pins that override or fill in whisper's guesses.
ANCHORS = [
    ('I have been having', 0, [(0, 0.15), (1, 2.0), (8, 6.2)]),
    ('All of you may die', 0, [(0, 10.0), (4, 10.4)]),
    ('I want off', 0, [(0, 25.0), (1, 25.3)]),
    ('AAAA', 0, [(0, 75.8)]),
    ('just disgusting', 0, [(0, 78.0), (1, 78.6)]),
    ('gambling with', 0, [(0, 80.6), (1, 82.0), (2, 82.6), (3, 84.4), (4, 86.3), (5, 88.2)]),
    ('perfectly safe', 0, [(0, 96.6), (1, 97.6)]),
    ('Felony bench', 0, [(0, 117.1)]),
    ('Pandemic bench', 0, [(0, 124.4), (1, 125.0), (2, 125.4), (3, 125.8), (4, 126.3), (5, 126.8), (6, 127.0)]),
    ('IM MAXIMIZING', 0, [(0, 127.8), (1, 128.2), (2, 130.0)]),
    ('AAAA', 1, [(0, 131.0)]),
    ('just disgusting', 1, [(0, 133.0), (1, 133.6)]),
    ('gambling with', 1, [(0, 135.4), (1, 137.2), (2, 137.7), (3, 139.0), (4, 140.3), (5, 141.6)]),
    ('If you ever', 0, [(0, 143.0), (1, 143.2), (2, 143.5), (3, 143.8), (4, 144.2)]),
    ('Goal become', 0, [(0, 173.6), (1, 174.0), (2, 174.4)]),
    ('AI WILL', 0, [(0, 178.9)]),
    ('AAAA', 2, [(0, 189.4)]),
    ('just disgusting', 2, [(0, 191.6), (1, 192.4)]),
    ('gambling with', 2, [(0, 194.3), (1, 196.0), (2, 197.0), (3, 198.0), (4, 199.9), (5, 201.2)]),
    ('Classify', 0, [(0, 202.3), (1, 202.8), (2, 202.9), (3, 203.3), (4, 203.9), (5, 204.1)]),
    ("It's pretty", 0, [(0, 204.8)]),
    ('A more intelligent', 0, [(0, 241.5), (1, 241.6), (2, 241.7), (3, 242.0), (4, 243.4), (5, 244.5), (6, 245.0), (7, 245.5)]),
    ("it's starting", 0, [(0, 29.0)]),
    ('Prove you', 0, [(11, 255.15), (12, 255.35), (13, 255.55)]),
    ('You made', 0, [(0, 255.75)]),
    ('What a time', 0, [(0, 262.4), (1, 263.1), (2, 263.4), (3, 264.5), (4, 264.9), (5, 265.4)]),
]
seen = {}
for li, l in enumerate(lines):
    for pre, occ, pins in ANCHORS:
        if l.lower().startswith(pre.lower()):
            k = (pre, seen.get(pre, 0))
            if k[1] == occ:
                for wi, t in pins: times[(li, wi)] = t
    for pre in {a[0] for a in ANCHORS}:
        if l.lower().startswith(pre.lower()): seen[pre] = seen.get(pre, 0) + 1

out, report = [], []
for li, ws in enumerate(toks):
    known = sorted((wi, times[(li, wi)]) for wi in range(len(ws)) if (li, wi) in times)
    if not known: sys.exit(f'line {li} has no timing: {lines[li]}')
    ts = []
    for wi in range(len(ws)):
        if (li, wi) in times: ts.append(times[(li, wi)]); continue
        before = [k for k in known if k[0] < wi]; after = [k for k in known if k[0] > wi]
        if before and after:
            (a, ta), (b, tb) = before[-1], after[0]; ts.append(ta + (tb - ta) * (wi - a) / (b - a))
        elif before: ts.append(before[-1][1] + 0.3 * (wi - before[-1][0]))
        else: ts.append(after[0][1] - 0.3 * (after[0][0] - wi))
    for i in range(1, len(ts)): ts[i] = max(ts[i], ts[i - 1] + 0.05)  # monotone
    out.append({'text': lines[li], 'words': [[round(t, 2), w] for t, w in zip(ts, ws)]})
    report.append(f'{ts[0]:7.2f} {ts[-1]:7.2f} {len(known):2d}/{len(ws):2d}  {lines[li][:70]}')
# a line stays up until shortly before the next one starts (at most 4 s after its last word)
for i, o in enumerate(out):
    nxt = out[i + 1]['words'][0][0] if i + 1 < len(out) else 999
    o['t0'] = round(o['words'][0][0] - 0.25, 2)
    o['t1'] = round(min(nxt - 0.3, o['words'][-1][0] + 4.0), 2)
if '--report' in sys.argv: print('\n'.join(report))
js = '// timing.js: generated by tools/align.py; do not edit by hand.\n'
js += f'const BPM = {BPM}, BEAT = 60 / BPM, OFF = {OFF};\n'
js += 'const LINES = [\n' + ',\n'.join('  ' + json.dumps(o, ensure_ascii=False) for o in out) + '\n];\n'
open('src/timing.js', 'w').write(js)
print(f'wrote src/timing.js: {len(out)} lines')
